services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/usr/src/app
    command: npm start
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "redis-cli", "-u", "redis://redis:6379", "ping"]
      interval: 10s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
